name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        uses: actions/setup-node@v1
      - name: Step 2
        run: >
          npm install -g bats
          bats -v
          echo "running jobs";
          echo "real";
          touch hello.txt;
      - name: Step 3
        uses: actions/upload-artifact@v2
        with:
          name: hello_file
          path: ./hello.txt
